### ISSUE TITLE
Code of Conduct page displays 404 Page Not Found

### ISSUE THREAD

**Issue by kryskreative** [cforlando/cfo-website#18]
## What is Wrong?
When a direct visitor goes to codefororlando.com/conduct in a browser, a Page Not Found message displays instead of Code of Conduct content. The title in the browser tab displays "Page Not Found".

## Steps To Reproduce

1. Open browser.
2. Type codefororlando.com/conduct in address bar, then press enter.
3. See error 

## What is Expected?
When a visitor types in codefororlando.com/conduct in the browser address bar, they land on the Code of Conduct page. Page title tag displays "Code of Conduct - Code for Orlando".

## Screenshots
Error page:
<img width="1435" alt="Screen Shot 2022-03-16 at 11 28 49 AM" src="https://user-images.githubusercontent.com/6386870/158633401-fb4d07b8-3144-42ae-8623-5f9eb12c4b53.png">

<img width="1068" alt="Screen Shot 2022-03-16 at 11 41 40 AM" src="https://user-images.githubusercontent.com/6386870/158635765-f5c797d9-3892-42f1-a43a-6a086fcd83bc.png">

### Technical Details
 - URL: codefororlando.com/conduct
 - Device: MacBook Pro (13'', 2019)
 - OS: macOS Catalina
 - Browser: Chrome 99

## Anything else we should know?
Brigade organizers and members frequently use the Code of Conduct to inform prospective and existing participants about expectations for Code for Orlando activities, events, and digital forums. The page URL is used in areas of agreement to provide additional information. Until this is resolved, Brigade organizers will be expected to use the [Code of Conduct repo](https://github.com/cforlando/codeofconduct).

**Comment by changeprogramming** [comment]
Thank you for the amount of info in this issue! We will need one piece of info before submitting a fix. May we have someone look at the Netlify [project's build settings](https://docs.netlify.com/configure-builds/overview/#basic-build-settings)? We need to know the value of the 'Publish directory'.

Thanks!

**Comment by kryskreative** [comment]
Great 👍 "build" is listed for the Publish directory.
